import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ConnectMetamask from "../../components/ConnectMetamask";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Rather Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <a
              href="https://www.ratherlabs.com/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <code className={styles.code}>Rather Labs Challenge</code>
            </a>
          </p>
          <div>
            <a
              href="https://github.com/LautiRad"
              target="_blank"
              rel="noopener noreferrer"
            >
              By <p>LautiRad</p>
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <ConnectMetamask />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Next.js <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Next.js Docs.</p>
          </a>
          <a
            href="https://web3js.readthedocs.io/en/v1.8.2/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Web3.js <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Web3.js Docs.</p>
          </a>
          <a
            href="https://www.typescriptlang.org/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              TypeScript <span>-&gt;</span>
            </h2>
            <p className={inter.className}>TypeScript Docs.</p>
          </a>
          <a
            href="https://ant.design/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Ant Design<span>-&gt;</span>
            </h2>
            <p className={inter.className}>Ant Design Docs.</p>
          </a>
        </div>
      </main>
    </>
  );
}
